SERVIDOR = 'mail.tecnoweb.org.bo'
PUERTO_POP = 110
PUERTO_SMTP = 25
USUARIO = 'grupo03cc'
CONTRASEÑA = 'grup003grup003'

NOMBRE_DB = 'db_'+USUARIO
USUARIO_DB = USUARIO
CONTRASEÑA_DB = CONTRASEÑA
HOST_DB = SERVIDOR